version: '3.8'
services:
  database:
    build: ./database
    environment:
      - POSTGRES_DB
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - DB_OPENBAR_PW
    ports:
      - "5433:5433"
    volumes:
      - ./postgres-data/postgres:/var/lib/postgresql/data
    restart: always
    healthcheck:
      test: ["CMD", "test" ,"-f", "/var/lib/postgresql/data/ready.flag"]
      interval: 1s
      timeout: 1s
      retries: 30
      start_period: 1s
    
  openbar:
    build: ./openbar
    links:
      - database
    depends_on:
      database:
        condition: service_healthy
    ports:
      - "5000:5000"
    environment:
      - ENV
      - DATABASE=postgresql://openbar:${DB_OPENBAR_PW}@database:5432/bar
      - BASE_URL=/api/v0/
      - SECRET_KEY
    volumes:
      - "./openbar/app:/opt/app"

  nginx:
    image: nginx:latest
    links:
      - openbar
    volumes:
      - "./nginx/default.conf:/etc/nginx/conf.d/default.conf"
    ports:
      - "8080:8080"
    restart: always
