version: '3'
services:
  database:
    build: ./database
    environment:
      - POSTGRES_DB
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - DB_SERVICE_USER_PW
      - DB_SERVICE_EXAMPLE_PW
    ports:
      - "5433:5433"
    volumes:
      - ./postgres-data-tests/postgres:/var/lib/postgresql/data
    restart: always
    healthcheck:
      test: ["CMD", "test" ,"-f", "/var/lib/postgresql/data/ready.flag"]
      interval: 1s
      timeout: 1s
      retries: 10
      start_period: 1s
  example-test:
    build: 
      context: ./example
      dockerfile: Dockerfile.test
    links:
      - database
    depends_on:
      database:
        condition: service_healthy
    environment:
      - FLASK_ENV
      - DATABASE=postgresql://service_example:${DB_SERVICE_EXAMPLE_PW}@database:5432/example
