FROM python:3 

RUN mkdir /opt/apt
COPY user/requirements-test.txt /opt/app/
WORKDIR /opt/app 

RUN python -m pip install --no-cache-dir --upgrade pip
RUN python -m pip install --no-cache-dir -r requirements-test.txt

COPY user/ /opt/app

RUN export FLASK_APP=app.py:create_app

ENTRYPOINT ["pytest" , "--cov=apis", "tests/"]
